🐛 Files not closed in catalog unit tests
The tests started to fail on Windows
with this error:

```
--- FAIL: TestCatalogNeedsUpdate (1.48s)
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestCatalogNeedsUpdate734870388\001\catalog.db: The process cannot access the file because it is being used by another process.
--- FAIL: TestCatalogExists (1.47s)
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestCatalogExists580267843\001\catalog.db: The process cannot access the file because it is being used by another process.
--- FAIL: Test_DownloadCatalog (1.58s)
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\Test_DownloadCatalog2314487335\001\catalog.db: The process cannot access the file because it is being used by another process.
```

The issue was that the files were not
closed, so the cleanup couldn't
delete the files.